# Generated by Django 5.2.4 on 2025-07-23 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'room_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('is_participant', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pokerroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.AddField(
            model_name='pokerroom',
            name='players',
            field=models.ManyToManyField(related_name='player_rooms', through='app.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
